
name: deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo SLACK_URL=${{ secrets.SLACK_URL }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo TEST_ACCESS_TOKEN=${{ secrets.TEST_ACCESS_TOKEN }} >> .env
          echo FIXED_ACCESS_TOKEN=${{ secrets.FIXED_ACCESS_TOKEN }} >> .env
          cat .env

      - name: build server files
        working-directory: ./
        run: |
          yarn
          yarn run build
      
      - name: zip file
        run: zip -r smeme.zip ./dist ./scripts ./appspec.yml ./.env ./package.json ./prisma
      
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./smeme.zip s3://smeme-bucket/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name smeme-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name smeme-group
          --s3-location bucket=smeme-bucket,bundleType=zip,key=deploy/smeme.zip